basePath: /v1
definitions:
  models.LoginRequest:
    properties:
      email:
        example: dealer@gmail.com
        type: string
      password:
        example: pass
        type: string
    type: object
  models.LoginResponse:
    properties:
      access_token:
        type: string
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Documentation
  title: Golang dealer APP
  version: "1.0"
paths:
  /admin/login:
    post:
      consumes:
      - application/json
      description: api for logging  in for admins
      operationId: admin-login
      parameters:
      - description: Admin credentials for logging in
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Login for admins
      tags:
      - admin
swagger: "2.0"
